### ISSUE TITLE
Write 4xx and 5xx status request log to error.log and redirect to stderr

### ISSUE THREAD

**Issue by qqbuby** [openresty/openresty#555]
Nginx writes the 4xx and 5xx log to file *error.log*, and the Nginx Docker image redirects the *access.log* to `stdout`, and redirects the *error.log* to `stderr`, so we can process docker and kubernetes log with a standard way. However, I found the `Nginx-Ingress-Controller` writes 4xx and 5xx log to `stdout`.

Is there any way to write the 4xx and 5xx log to *error.log* ?

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxz
  name: nginxz
spec:
  selector:
    app: nginxz
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32015
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxz
  name: nginxz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxz
  template:
    metadata:
      labels:
        app: nginxz
    spec:
      containers:
        - image: openresty/openresty:1.15.8.2-4-buster
          name: nginx
```

```
$ curl -iI localhost:32015/404notfound
HTTP/1.1 404 Not Found
Server: openresty/1.15.8.2
Date: Wed, 13 Nov 2019 07:36:26 GMT
Content-Type: text/html
Content-Length: 159
Connection: keep-alive
```

```
# cat /var/lib/docker/containers/376e0c9c0cdba9f7d8aa589f70717ba42391269d16944a84a92b61b217f3b17d/376e0c9c0cdba9f7d8aa589f70717ba42391269d16944a84a92b61b217f3b17d-json.log
{"log":"2019/11/13 07:36:26 [error] 9#9: *1 open() \"/usr/local/openresty/nginx/html/404notfound\" failed (2: No such file or directory), client: 10.244.0.1, server: localhost, request: \"HEAD /404notfound HTTP/1.1\", host: \"192.168.127.128:32015\"\n","stream":"stderr","time":"2019-11-13T07:36:26.338586414Z"}
{"log":"10.244.0.1 - - [13/Nov/2019:07:36:26 +0000] \"HEAD /404notfound HTTP/1.1\" 404 0 \"-\" \"curl/7.64.0\"\n","stream":"stdout","time":"2019-11-13T07:36:26.338601767Z"}
```
